// NOTE: This file is auto-generated by scripts/endpoint_typegen.ts

import { snowflake } from "./common.ts";

/**
 * Get My Oauth2 Application
 * @method GET
 */
export type GetMyOauth2ApplicationEndpoint = `/oauth2/applications/@me`;

/**
 * List My Connections
 * @method GET
 */
export type ListMyConnectionsEndpoint = `/users/@me/connections`;

/**
 * Create Dm
 * @method POST
 */
export type CreateDmEndpoint = `/users/@me/channels`;

/**
 * List My Guilds
 * @method GET
 */
export type ListMyGuildsEndpoint = `/users/@me/guilds`;

/**
 * Get My Application
 * @method GET
 */
export type GetMyApplicationEndpoint = `/applications/@me`;

/**
 * Update My Application
 * @method PATCH
 */
export type UpdateMyApplicationEndpoint = `/applications/@me`;

/**
 * Get Bot Gateway
 * @method GET
 */
export type GetBotGatewayEndpoint = `/gateway/bot`;

/**
 * Get My Oauth2 Authorization
 * @method GET
 */
export type GetMyOauth2AuthorizationEndpoint = `/oauth2/@me`;

/**
 * List Voice Regions
 * @method GET
 */
export type ListVoiceRegionsEndpoint = `/voice/regions`;

/**
 * Get My User
 * @method GET
 */
export type GetMyUserEndpoint = `/users/@me`;

/**
 * Update My User
 * @method PATCH
 */
export type UpdateMyUserEndpoint = `/users/@me`;

/**
 * Create Stage Instance
 * @method POST
 */
export type CreateStageInstanceEndpoint = `/stage-instances`;

/**
 * List Sticker Packs
 * @method GET
 */
export type ListStickerPacksEndpoint = `/sticker-packs`;

/**
 * Get Gateway
 * @method GET
 */
export type GetGatewayEndpoint = `/gateway`;

/**
 * Create Guild
 * @method POST
 */
export type CreateGuildEndpoint = `/guilds`;

/**
 * List My Private Archived Threads
 * @method GET
 */
export type ListMyPrivateArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/users/@me/threads/archived/private`;

/**
 * List Guild Application Command Permissions
 * @method GET
 */
export type ListGuildApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/permissions`;

/**
 * Get Guild Application Command Permissions
 * @method GET
 */
export type GetGuildApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> =
  `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}/permissions`;

/**
 * Set Guild Application Command Permissions
 * @method PUT
 */
export type SetGuildApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> =
  `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}/permissions`;

/**
 * Add My Message Reaction
 * @method PUT
 */
export type AddMyMessageReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  EmojiName extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${EmojiName}/@me`;

/**
 * Delete My Message Reaction
 * @method DELETE
 */
export type DeleteMyMessageReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  EmojiName extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${EmojiName}/@me`;

/**
 * List Private Archived Threads
 * @method GET
 */
export type ListPrivateArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads/archived/private`;

/**
 * List Public Archived Threads
 * @method GET
 */
export type ListPublicArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads/archived/public`;

/**
 * Get Application User Role Connection
 * @method GET
 */
export type GetApplicationUserRoleConnectionEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/users/@me/applications/${ApplicationID}/role-connection`;

/**
 * Update Application User Role Connection
 * @method PUT
 */
export type UpdateApplicationUserRoleConnectionEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/users/@me/applications/${ApplicationID}/role-connection`;

/**
 * Get My Guild Member
 * @method GET
 */
export type GetMyGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
> = `/users/@me/guilds/${GuildID}/member`;

/**
 * Get Application Role Connections Metadata
 * @method GET
 */
export type GetApplicationRoleConnectionsMetadataEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/role-connections/metadata`;

/**
 * Update Application Role Connections Metadata
 * @method PUT
 */
export type UpdateApplicationRoleConnectionsMetadataEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/role-connections/metadata`;

/**
 * Get Guild Application Command
 * @method GET
 */
export type GetGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * Delete Guild Application Command
 * @method DELETE
 */
export type DeleteGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * Update Guild Application Command
 * @method PATCH
 */
export type UpdateGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * List Guild Application Commands
 * @method GET
 */
export type ListGuildApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Bulk Set Guild Application Commands
 * @method PUT
 */
export type BulkSetGuildApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Create Guild Application Command
 * @method POST
 */
export type CreateGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Join Thread
 * @method PUT
 */
export type JoinThreadEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/@me`;

/**
 * Leave Thread
 * @method DELETE
 */
export type LeaveThreadEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/@me`;

/**
 * Bulk Delete Messages
 * @method POST
 */
export type BulkDeleteMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/bulk-delete`;

/**
 * Delete User Message Reaction
 * @method DELETE
 */
export type DeleteUserMessageReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  EmojiName extends string = string,
  UserID extends snowflake = snowflake,
> =
  `/channels/${ChannelID}/messages/${MessageID}/reactions/${EmojiName}/${UserID}`;

/**
 * List Message Reactions By Emoji
 * @method GET
 */
export type ListMessageReactionsByEmojiEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  EmojiName extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${EmojiName}`;

/**
 * Delete All Message Reactions By Emoji
 * @method DELETE
 */
export type DeleteAllMessageReactionsByEmojiEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  EmojiName extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${EmojiName}`;

/**
 * Delete All Message Reactions
 * @method DELETE
 */
export type DeleteAllMessageReactionsEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions`;

/**
 * Crosspost Message
 * @method POST
 */
export type CrosspostMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/crosspost`;

/**
 * Create Thread From Message
 * @method POST
 */
export type CreateThreadFromMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/threads`;

/**
 * Get Original Webhook Message
 * @method GET
 */
export type GetOriginalWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/@original`;

/**
 * Delete Original Webhook Message
 * @method DELETE
 */
export type DeleteOriginalWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/@original`;

/**
 * Update Original Webhook Message
 * @method PATCH
 */
export type UpdateOriginalWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/@original`;

/**
 * List Guild Scheduled Event Users
 * @method GET
 */
export type ListGuildScheduledEventUsersEndpoint<
  GuildID extends snowflake = snowflake,
  GuildScheduledEventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${GuildScheduledEventID}/users`;

/**
 * Get Auto Moderation Rule
 * @method GET
 */
export type GetAutoModerationRuleEndpoint<
  GuildID extends snowflake = snowflake,
  RuleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/auto-moderation/rules/${RuleID}`;

/**
 * Delete Auto Moderation Rule
 * @method DELETE
 */
export type DeleteAutoModerationRuleEndpoint<
  GuildID extends snowflake = snowflake,
  RuleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/auto-moderation/rules/${RuleID}`;

/**
 * Update Auto Moderation Rule
 * @method PATCH
 */
export type UpdateAutoModerationRuleEndpoint<
  GuildID extends snowflake = snowflake,
  RuleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/auto-moderation/rules/${RuleID}`;

/**
 * List Auto Moderation Rules
 * @method GET
 */
export type ListAutoModerationRulesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/auto-moderation/rules`;

/**
 * Create Auto Moderation Rule
 * @method POST
 */
export type CreateAutoModerationRuleEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/auto-moderation/rules`;

/**
 * Update Self Voice State
 * @method PATCH
 */
export type UpdateSelfVoiceStateEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/voice-states/@me`;

/**
 * Search Guild Members
 * @method GET
 */
export type SearchGuildMembersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/search`;

/**
 * Get Active Guild Threads
 * @method GET
 */
export type GetActiveGuildThreadsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/threads/active`;

/**
 * Update My Guild Member
 * @method PATCH
 */
export type UpdateMyGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/@me`;

/**
 * Add Guild Member Role
 * @method PUT
 */
export type AddGuildMemberRoleEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}/roles/${RoleID}`;

/**
 * Delete Guild Member Role
 * @method DELETE
 */
export type DeleteGuildMemberRoleEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}/roles/${RoleID}`;

/**
 * Leave Guild
 * @method DELETE
 */
export type LeaveGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/users/@me/guilds/${GuildID}`;

/**
 * Get Application Command
 * @method GET
 */
export type GetApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * Delete Application Command
 * @method DELETE
 */
export type DeleteApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * Update Application Command
 * @method PATCH
 */
export type UpdateApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * List Application Commands
 * @method GET
 */
export type ListApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Bulk Set Application Commands
 * @method PUT
 */
export type BulkSetApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Create Application Command
 * @method POST
 */
export type CreateApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Create Interaction Response
 * @method POST
 */
export type CreateInteractionResponseEndpoint<
  InteractionID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/interactions/${InteractionID}/${InteractionToken}/callback`;

/**
 * Get Thread Member
 * @method GET
 */
export type GetThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * Add Thread Member
 * @method PUT
 */
export type AddThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * Delete Thread Member
 * @method DELETE
 */
export type DeleteThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * List Thread Members
 * @method GET
 */
export type ListThreadMembersEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members`;

/**
 * Set Channel Permission Overwrite
 * @method PUT
 */
export type SetChannelPermissionOverwriteEndpoint<
  ChannelID extends snowflake = snowflake,
  OverwriteID extends snowflake = snowflake,
> = `/channels/${ChannelID}/permissions/${OverwriteID}`;

/**
 * Delete Channel Permission Overwrite
 * @method DELETE
 */
export type DeleteChannelPermissionOverwriteEndpoint<
  ChannelID extends snowflake = snowflake,
  OverwriteID extends snowflake = snowflake,
> = `/channels/${ChannelID}/permissions/${OverwriteID}`;

/**
 * Add Group Dm User
 * @method PUT
 */
export type AddGroupDmUserEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/recipients/${UserID}`;

/**
 * Delete Group Dm User
 * @method DELETE
 */
export type DeleteGroupDmUserEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/recipients/${UserID}`;

/**
 * Follow Channel
 * @method POST
 */
export type FollowChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/followers`;

/**
 * Get Message
 * @method GET
 */
export type GetMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * Delete Message
 * @method DELETE
 */
export type DeleteMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * Update Message
 * @method PATCH
 */
export type UpdateMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * List Messages
 * @method GET
 */
export type ListMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages`;

/**
 * Create Message
 * @method POST
 */
export type CreateMessageEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages`;

/**
 * List Channel Webhooks
 * @method GET
 */
export type ListChannelWebhooksEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/webhooks`;

/**
 * Create Webhook
 * @method POST
 */
export type CreateWebhookEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/webhooks`;

/**
 * List Channel Invites
 * @method GET
 */
export type ListChannelInvitesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/invites`;

/**
 * Create Channel Invite
 * @method POST
 */
export type CreateChannelInviteEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/invites`;

/**
 * Create Thread
 * @method POST
 */
export type CreateThreadEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads`;

/**
 * Trigger Typing Indicator
 * @method POST
 */
export type TriggerTypingIndicatorEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/typing`;

/**
 * Pin Message
 * @method PUT
 */
export type PinMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins/${MessageID}`;

/**
 * Unpin Message
 * @method DELETE
 */
export type UnpinMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins/${MessageID}`;

/**
 * List Pinned Messages
 * @method GET
 */
export type ListPinnedMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins`;

/**
 * Get Webhook Message
 * @method GET
 */
export type GetWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Delete Webhook Message
 * @method DELETE
 */
export type DeleteWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Update Webhook Message
 * @method PATCH
 */
export type UpdateWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Execute Github Compatible Webhook
 * @method POST
 */
export type ExecuteGithubCompatibleWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/github`;

/**
 * Execute Slack Compatible Webhook
 * @method POST
 */
export type ExecuteSlackCompatibleWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/slack`;

/**
 * Get Guild Template
 * @method GET
 */
export type GetGuildTemplateEndpoint<
  Code extends string = string,
> = `/guilds/templates/${Code}`;

/**
 * Create Guild From Template
 * @method POST
 */
export type CreateGuildFromTemplateEndpoint<
  Code extends string = string,
> = `/guilds/templates/${Code}`;

/**
 * Get Guild New Member Welcome
 * @method GET
 */
export type GetGuildNewMemberWelcomeEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/new-member-welcome`;

/**
 * Get Guild Scheduled Event
 * @method GET
 */
export type GetGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  GuildScheduledEventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${GuildScheduledEventID}`;

/**
 * Delete Guild Scheduled Event
 * @method DELETE
 */
export type DeleteGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  GuildScheduledEventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${GuildScheduledEventID}`;

/**
 * Update Guild Scheduled Event
 * @method PATCH
 */
export type UpdateGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  GuildScheduledEventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${GuildScheduledEventID}`;

/**
 * List Guild Scheduled Events
 * @method GET
 */
export type ListGuildScheduledEventsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events`;

/**
 * Create Guild Scheduled Event
 * @method POST
 */
export type CreateGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events`;

/**
 * Get Guild Welcome Screen
 * @method GET
 */
export type GetGuildWelcomeScreenEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/welcome-screen`;

/**
 * Update Guild Welcome Screen
 * @method PATCH
 */
export type UpdateGuildWelcomeScreenEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/welcome-screen`;

/**
 * Update Voice State
 * @method PATCH
 */
export type UpdateVoiceStateEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/voice-states/${UserID}`;

/**
 * Delete Guild Integration
 * @method DELETE
 */
export type DeleteGuildIntegrationEndpoint<
  GuildID extends snowflake = snowflake,
  IntegrationID extends snowflake = snowflake,
> = `/guilds/${GuildID}/integrations/${IntegrationID}`;

/**
 * List Guild Integrations
 * @method GET
 */
export type ListGuildIntegrationsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/integrations`;

/**
 * Get Guild Widget
 * @method GET
 */
export type GetGuildWidgetEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget.json`;

/**
 * Get Guilds Onboarding
 * @method GET
 */
export type GetGuildsOnboardingEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/onboarding`;

/**
 * Put Guilds Onboarding
 * @method PUT
 */
export type PutGuildsOnboardingEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/onboarding`;

/**
 * Get Guild Vanity Url
 * @method GET
 */
export type GetGuildVanityUrlEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/vanity-url`;

/**
 * List Guild Audit Log Entries
 * @method GET
 */
export type ListGuildAuditLogEntriesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/audit-logs`;

/**
 * Get Guild Widget Png
 * @method GET
 */
export type GetGuildWidgetPngEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget.png`;

/**
 * Sync Guild Template
 * @method PUT
 */
export type SyncGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  Code extends string = string,
> = `/guilds/${GuildID}/templates/${Code}`;

/**
 * Delete Guild Template
 * @method DELETE
 */
export type DeleteGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  Code extends string = string,
> = `/guilds/${GuildID}/templates/${Code}`;

/**
 * Update Guild Template
 * @method PATCH
 */
export type UpdateGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  Code extends string = string,
> = `/guilds/${GuildID}/templates/${Code}`;

/**
 * List Guild Templates
 * @method GET
 */
export type ListGuildTemplatesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/templates`;

/**
 * Create Guild Template
 * @method POST
 */
export type CreateGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/templates`;

/**
 * Get Guild Sticker
 * @method GET
 */
export type GetGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * Delete Guild Sticker
 * @method DELETE
 */
export type DeleteGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * Update Guild Sticker
 * @method PATCH
 */
export type UpdateGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * List Guild Channels
 * @method GET
 */
export type ListGuildChannelsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * Create Guild Channel
 * @method POST
 */
export type CreateGuildChannelEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * Bulk Update Guild Channels
 * @method PATCH
 */
export type BulkUpdateGuildChannelsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * List Guild Stickers
 * @method GET
 */
export type ListGuildStickersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers`;

/**
 * Create Guild Sticker
 * @method POST
 */
export type CreateGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers`;

/**
 * Get Guild Webhooks
 * @method GET
 */
export type GetGuildWebhooksEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/webhooks`;

/**
 * Get Guild Member
 * @method GET
 */
export type GetGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Add Guild Member
 * @method PUT
 */
export type AddGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Delete Guild Member
 * @method DELETE
 */
export type DeleteGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Update Guild Member
 * @method PATCH
 */
export type UpdateGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * List Guild Members
 * @method GET
 */
export type ListGuildMembersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members`;

/**
 * Get Guild Preview
 * @method GET
 */
export type GetGuildPreviewEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/preview`;

/**
 * List Guild Invites
 * @method GET
 */
export type ListGuildInvitesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/invites`;

/**
 * List Guild Voice Regions
 * @method GET
 */
export type ListGuildVoiceRegionsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/regions`;

/**
 * Get Guild Emoji
 * @method GET
 */
export type GetGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * Delete Guild Emoji
 * @method DELETE
 */
export type DeleteGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * Update Guild Emoji
 * @method PATCH
 */
export type UpdateGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * List Guild Emojis
 * @method GET
 */
export type ListGuildEmojisEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis`;

/**
 * Create Guild Emoji
 * @method POST
 */
export type CreateGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis`;

/**
 * Get Guild Widget Settings
 * @method GET
 */
export type GetGuildWidgetSettingsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget`;

/**
 * Update Guild Widget Settings
 * @method PATCH
 */
export type UpdateGuildWidgetSettingsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget`;

/**
 * Delete Guild Role
 * @method DELETE
 */
export type DeleteGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles/${RoleID}`;

/**
 * Update Guild Role
 * @method PATCH
 */
export type UpdateGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles/${RoleID}`;

/**
 * List Guild Roles
 * @method GET
 */
export type ListGuildRolesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Create Guild Role
 * @method POST
 */
export type CreateGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Bulk Update Guild Roles
 * @method PATCH
 */
export type BulkUpdateGuildRolesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Preview Prune Guild
 * @method GET
 */
export type PreviewPruneGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/prune`;

/**
 * Prune Guild
 * @method POST
 */
export type PruneGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/prune`;

/**
 * Get Guild Ban
 * @method GET
 */
export type GetGuildBanEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * Ban User From Guild
 * @method PUT
 */
export type BanUserFromGuildEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * Unban User From Guild
 * @method DELETE
 */
export type UnbanUserFromGuildEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * List Guild Bans
 * @method GET
 */
export type ListGuildBansEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans`;

/**
 * Set Guild Mfa Level
 * @method POST
 */
export type SetGuildMfaLevelEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/mfa`;

/**
 * Get Stage Instance
 * @method GET
 */
export type GetStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Delete Stage Instance
 * @method DELETE
 */
export type DeleteStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Update Stage Instance
 * @method PATCH
 */
export type UpdateStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Get Application
 * @method GET
 */
export type GetApplicationEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}`;

/**
 * Update Application
 * @method PATCH
 */
export type UpdateApplicationEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}`;

/**
 * Get Webhook By Token
 * @method GET
 */
export type GetWebhookByTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Execute Webhook
 * @method POST
 */
export type ExecuteWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Delete Webhook By Token
 * @method DELETE
 */
export type DeleteWebhookByTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Update Webhook By Token
 * @method PATCH
 */
export type UpdateWebhookByTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Get Channel
 * @method GET
 */
export type GetChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}`;

/**
 * Delete Channel
 * @method DELETE
 */
export type DeleteChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}`;

/**
 * Update Channel
 * @method PATCH
 */
export type UpdateChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}`;

/**
 * Get Sticker
 * @method GET
 */
export type GetStickerEndpoint<
  StickerID extends snowflake = snowflake,
> = `/stickers/${StickerID}`;

/**
 * Get Webhook
 * @method GET
 */
export type GetWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Delete Webhook
 * @method DELETE
 */
export type DeleteWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Update Webhook
 * @method PATCH
 */
export type UpdateWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Invite Resolve
 * @method GET
 */
export type InviteResolveEndpoint<
  Code extends string = string,
> = `/invites/${Code}`;

/**
 * Invite Revoke
 * @method DELETE
 */
export type InviteRevokeEndpoint<
  Code extends string = string,
> = `/invites/${Code}`;

/**
 * Get Guild
 * @method GET
 */
export type GetGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Delete Guild
 * @method DELETE
 */
export type DeleteGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Update Guild
 * @method PATCH
 */
export type UpdateGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Get User
 * @method GET
 */
export type GetUserEndpoint<
  UserID extends snowflake = snowflake,
> = `/users/${UserID}`;

export type Endpoint =
  | GetMyOauth2ApplicationEndpoint
  | ListMyConnectionsEndpoint
  | CreateDmEndpoint
  | ListMyGuildsEndpoint
  | GetMyApplicationEndpoint
  | UpdateMyApplicationEndpoint
  | GetBotGatewayEndpoint
  | GetMyOauth2AuthorizationEndpoint
  | ListVoiceRegionsEndpoint
  | GetMyUserEndpoint
  | UpdateMyUserEndpoint
  | CreateStageInstanceEndpoint
  | ListStickerPacksEndpoint
  | GetGatewayEndpoint
  | CreateGuildEndpoint
  | ListMyPrivateArchivedThreadsEndpoint
  | ListGuildApplicationCommandPermissionsEndpoint
  | GetGuildApplicationCommandPermissionsEndpoint
  | SetGuildApplicationCommandPermissionsEndpoint
  | AddMyMessageReactionEndpoint
  | DeleteMyMessageReactionEndpoint
  | ListPrivateArchivedThreadsEndpoint
  | ListPublicArchivedThreadsEndpoint
  | GetApplicationUserRoleConnectionEndpoint
  | UpdateApplicationUserRoleConnectionEndpoint
  | GetMyGuildMemberEndpoint
  | GetApplicationRoleConnectionsMetadataEndpoint
  | UpdateApplicationRoleConnectionsMetadataEndpoint
  | GetGuildApplicationCommandEndpoint
  | DeleteGuildApplicationCommandEndpoint
  | UpdateGuildApplicationCommandEndpoint
  | ListGuildApplicationCommandsEndpoint
  | BulkSetGuildApplicationCommandsEndpoint
  | CreateGuildApplicationCommandEndpoint
  | JoinThreadEndpoint
  | LeaveThreadEndpoint
  | BulkDeleteMessagesEndpoint
  | DeleteUserMessageReactionEndpoint
  | ListMessageReactionsByEmojiEndpoint
  | DeleteAllMessageReactionsByEmojiEndpoint
  | DeleteAllMessageReactionsEndpoint
  | CrosspostMessageEndpoint
  | CreateThreadFromMessageEndpoint
  | GetOriginalWebhookMessageEndpoint
  | DeleteOriginalWebhookMessageEndpoint
  | UpdateOriginalWebhookMessageEndpoint
  | ListGuildScheduledEventUsersEndpoint
  | GetAutoModerationRuleEndpoint
  | DeleteAutoModerationRuleEndpoint
  | UpdateAutoModerationRuleEndpoint
  | ListAutoModerationRulesEndpoint
  | CreateAutoModerationRuleEndpoint
  | UpdateSelfVoiceStateEndpoint
  | SearchGuildMembersEndpoint
  | GetActiveGuildThreadsEndpoint
  | UpdateMyGuildMemberEndpoint
  | AddGuildMemberRoleEndpoint
  | DeleteGuildMemberRoleEndpoint
  | LeaveGuildEndpoint
  | GetApplicationCommandEndpoint
  | DeleteApplicationCommandEndpoint
  | UpdateApplicationCommandEndpoint
  | ListApplicationCommandsEndpoint
  | BulkSetApplicationCommandsEndpoint
  | CreateApplicationCommandEndpoint
  | CreateInteractionResponseEndpoint
  | GetThreadMemberEndpoint
  | AddThreadMemberEndpoint
  | DeleteThreadMemberEndpoint
  | ListThreadMembersEndpoint
  | SetChannelPermissionOverwriteEndpoint
  | DeleteChannelPermissionOverwriteEndpoint
  | AddGroupDmUserEndpoint
  | DeleteGroupDmUserEndpoint
  | FollowChannelEndpoint
  | GetMessageEndpoint
  | DeleteMessageEndpoint
  | UpdateMessageEndpoint
  | ListMessagesEndpoint
  | CreateMessageEndpoint
  | ListChannelWebhooksEndpoint
  | CreateWebhookEndpoint
  | ListChannelInvitesEndpoint
  | CreateChannelInviteEndpoint
  | CreateThreadEndpoint
  | TriggerTypingIndicatorEndpoint
  | PinMessageEndpoint
  | UnpinMessageEndpoint
  | ListPinnedMessagesEndpoint
  | GetWebhookMessageEndpoint
  | DeleteWebhookMessageEndpoint
  | UpdateWebhookMessageEndpoint
  | ExecuteGithubCompatibleWebhookEndpoint
  | ExecuteSlackCompatibleWebhookEndpoint
  | GetGuildTemplateEndpoint
  | CreateGuildFromTemplateEndpoint
  | GetGuildNewMemberWelcomeEndpoint
  | GetGuildScheduledEventEndpoint
  | DeleteGuildScheduledEventEndpoint
  | UpdateGuildScheduledEventEndpoint
  | ListGuildScheduledEventsEndpoint
  | CreateGuildScheduledEventEndpoint
  | GetGuildWelcomeScreenEndpoint
  | UpdateGuildWelcomeScreenEndpoint
  | UpdateVoiceStateEndpoint
  | DeleteGuildIntegrationEndpoint
  | ListGuildIntegrationsEndpoint
  | GetGuildWidgetEndpoint
  | GetGuildsOnboardingEndpoint
  | PutGuildsOnboardingEndpoint
  | GetGuildVanityUrlEndpoint
  | ListGuildAuditLogEntriesEndpoint
  | GetGuildWidgetPngEndpoint
  | SyncGuildTemplateEndpoint
  | DeleteGuildTemplateEndpoint
  | UpdateGuildTemplateEndpoint
  | ListGuildTemplatesEndpoint
  | CreateGuildTemplateEndpoint
  | GetGuildStickerEndpoint
  | DeleteGuildStickerEndpoint
  | UpdateGuildStickerEndpoint
  | ListGuildChannelsEndpoint
  | CreateGuildChannelEndpoint
  | BulkUpdateGuildChannelsEndpoint
  | ListGuildStickersEndpoint
  | CreateGuildStickerEndpoint
  | GetGuildWebhooksEndpoint
  | GetGuildMemberEndpoint
  | AddGuildMemberEndpoint
  | DeleteGuildMemberEndpoint
  | UpdateGuildMemberEndpoint
  | ListGuildMembersEndpoint
  | GetGuildPreviewEndpoint
  | ListGuildInvitesEndpoint
  | ListGuildVoiceRegionsEndpoint
  | GetGuildEmojiEndpoint
  | DeleteGuildEmojiEndpoint
  | UpdateGuildEmojiEndpoint
  | ListGuildEmojisEndpoint
  | CreateGuildEmojiEndpoint
  | GetGuildWidgetSettingsEndpoint
  | UpdateGuildWidgetSettingsEndpoint
  | DeleteGuildRoleEndpoint
  | UpdateGuildRoleEndpoint
  | ListGuildRolesEndpoint
  | CreateGuildRoleEndpoint
  | BulkUpdateGuildRolesEndpoint
  | PreviewPruneGuildEndpoint
  | PruneGuildEndpoint
  | GetGuildBanEndpoint
  | BanUserFromGuildEndpoint
  | UnbanUserFromGuildEndpoint
  | ListGuildBansEndpoint
  | SetGuildMfaLevelEndpoint
  | GetStageInstanceEndpoint
  | DeleteStageInstanceEndpoint
  | UpdateStageInstanceEndpoint
  | GetApplicationEndpoint
  | UpdateApplicationEndpoint
  | GetWebhookByTokenEndpoint
  | ExecuteWebhookEndpoint
  | DeleteWebhookByTokenEndpoint
  | UpdateWebhookByTokenEndpoint
  | GetChannelEndpoint
  | DeleteChannelEndpoint
  | UpdateChannelEndpoint
  | GetStickerEndpoint
  | GetWebhookEndpoint
  | DeleteWebhookEndpoint
  | UpdateWebhookEndpoint
  | InviteResolveEndpoint
  | InviteRevokeEndpoint
  | GetGuildEndpoint
  | DeleteGuildEndpoint
  | UpdateGuildEndpoint
  | GetUserEndpoint;
