// NOTE: This file is auto-generated by scripts/endpoint_typegen.ts

import { snowflake } from "./common.ts";

/**
 * Create Interaction Response
 * @method POST
 */
export type CreateInteractionResponseEndpoint<
  InteractionID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/interactions/${InteractionID}/${InteractionToken}/callback`;

/**
 * Get Original Interaction Response
 * @method GET
 */
export type GetOriginalInteractionResponseEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/@original`;

/**
 * Edit Original Interaction Response
 * @method PATCH
 */
export type EditOriginalInteractionResponseEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/@original`;

/**
 * Delete Original Interaction Response
 * @method DELETE
 */
export type DeleteOriginalInteractionResponseEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/@original`;

/**
 * Create Followup Message
 * @method POST
 */
export type CreateFollowupMessageEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
> = `/webhooks/${ApplicationID}/${InteractionToken}`;

/**
 * Get Followup Message
 * @method GET
 */
export type GetFollowupMessageEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/${MessageID}`;

/**
 * Edit Followup Message
 * @method PATCH
 */
export type EditFollowupMessageEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/${MessageID}`;

/**
 * Delete Followup Message
 * @method DELETE
 */
export type DeleteFollowupMessageEndpoint<
  ApplicationID extends snowflake = snowflake,
  InteractionToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${ApplicationID}/${InteractionToken}/messages/${MessageID}`;

/**
 * Get Global Application Commands
 * @method GET
 */
export type GetGlobalApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Create Global Application Command
 * @method POST
 */
export type CreateGlobalApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Get Global Application Command
 * @method GET
 */
export type GetGlobalApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * Edit Global Application Command
 * @method PATCH
 */
export type EditGlobalApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * Delete Global Application Command
 * @method DELETE
 */
export type DeleteGlobalApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands/${CommandID}`;

/**
 * Bulk Overwrite Global Application Commands
 * @method PUT
 */
export type BulkOverwriteGlobalApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/commands`;

/**
 * Get Guild Application Commands
 * @method GET
 */
export type GetGuildApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Create Guild Application Command
 * @method POST
 */
export type CreateGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Get Guild Application Command
 * @method GET
 */
export type GetGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * Edit Guild Application Command
 * @method PATCH
 */
export type EditGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * Delete Guild Application Command
 * @method DELETE
 */
export type DeleteGuildApplicationCommandEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}`;

/**
 * Bulk Overwrite Guild Application Commands
 * @method PUT
 */
export type BulkOverwriteGuildApplicationCommandsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands`;

/**
 * Get Guild Application Command Permissions
 * @method GET
 */
export type GetGuildApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/permissions`;

/**
 * Get Application Command Permissions
 * @method GET
 */
export type GetApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> =
  `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}/permissions`;

/**
 * Edit Application Command Permissions
 * @method PUT
 */
export type EditApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
  CommandID extends snowflake = snowflake,
> =
  `/applications/${ApplicationID}/guilds/${GuildID}/commands/${CommandID}/permissions`;

/**
 * Batch Edit Application Command Permissions
 * @method PUT
 */
export type BatchEditApplicationCommandPermissionsEndpoint<
  ApplicationID extends snowflake = snowflake,
  GuildID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/guilds/${GuildID}/commands/permissions`;

/**
 * Create Webhook
 * @method POST
 */
export type CreateWebhookEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/webhooks`;

/**
 * Get Channel Webhooks
 * @method GET
 */
export type GetChannelWebhooksEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/webhooks`;

/**
 * Get Guild Webhooks
 * @method GET
 */
export type GetGuildWebhooksEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/webhooks`;

/**
 * Get Webhook
 * @method GET
 */
export type GetWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Get Webhook with Token
 * @method GET
 */
export type GetWebhookwithTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Edit Webhook
 * @method PATCH
 */
export type EditWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Edit Webhook with Token
 * @method PATCH
 */
export type EditWebhookwithTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Delete Webhook
 * @method DELETE
 */
export type DeleteWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}`;

/**
 * Delete Webhook with Token
 * @method DELETE
 */
export type DeleteWebhookwithTokenEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Execute Webhook
 * @method POST
 */
export type ExecuteWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}`;

/**
 * Execute Slack-Compatible Webhook
 * @method POST
 */
export type ExecuteSlackCompatibleWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/slack`;

/**
 * Execute GitHub-Compatible Webhook
 * @method POST
 */
export type ExecuteGitHubCompatibleWebhookEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
> = `/webhooks/${WebhookID}/${WebhookToken}/github`;

/**
 * Get Webhook Message
 * @method GET
 */
export type GetWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Edit Webhook Message
 * @method PATCH
 */
export type EditWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Delete Webhook Message
 * @method DELETE
 */
export type DeleteWebhookMessageEndpoint<
  WebhookID extends snowflake = snowflake,
  WebhookToken extends string = string,
  MessageID extends snowflake = snowflake,
> = `/webhooks/${WebhookID}/${WebhookToken}/messages/${MessageID}`;

/**
 * Create Guild
 * @method POST
 */
export type CreateGuildEndpoint = `/guilds`;

/**
 * Get Guild
 * @method GET
 */
export type GetGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Get Guild Preview
 * @method GET
 */
export type GetGuildPreviewEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/preview`;

/**
 * Edit Guild
 * @method PATCH
 */
export type EditGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Delete Guild
 * @method DELETE
 */
export type DeleteGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}`;

/**
 * Get Guild Channels
 * @method GET
 */
export type GetGuildChannelsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * Create Guild Channel
 * @method POST
 */
export type CreateGuildChannelEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * Edit Guild Channel Positions
 * @method PATCH
 */
export type EditGuildChannelPositionsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/channels`;

/**
 * List Active Guild Threads
 * @method GET
 */
export type ListActiveGuildThreadsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/threads/active`;

/**
 * Get Guild Member
 * @method GET
 */
export type GetGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * List Guild Members
 * @method GET
 */
export type ListGuildMembersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members`;

/**
 * Search Guild Members
 * @method GET
 */
export type SearchGuildMembersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/search`;

/**
 * Add Guild Member
 * @method PUT
 */
export type AddGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Edit Guild Member
 * @method PATCH
 */
export type EditGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Edit Current Member
 * @method PATCH
 */
export type EditCurrentMemberEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/@me`;

/**
 * Edit Current User Nick
 * @method PATCH
 */
export type EditCurrentUserNickEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/@me/nick`;

/**
 * Add Guild Member Role
 * @method PUT
 */
export type AddGuildMemberRoleEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}/roles/${RoleID}`;

/**
 * Remove Guild Member Role
 * @method DELETE
 */
export type RemoveGuildMemberRoleEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}/roles/${RoleID}`;

/**
 * Remove Guild Member
 * @method DELETE
 */
export type RemoveGuildMemberEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/members/${UserID}`;

/**
 * Get Guild Bans
 * @method GET
 */
export type GetGuildBansEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans`;

/**
 * Get Guild Ban
 * @method GET
 */
export type GetGuildBanEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * Create Guild Ban
 * @method PUT
 */
export type CreateGuildBanEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * Remove Guild Ban
 * @method DELETE
 */
export type RemoveGuildBanEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/bans/${UserID}`;

/**
 * Get Guild Roles
 * @method GET
 */
export type GetGuildRolesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Create Guild Role
 * @method POST
 */
export type CreateGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Edit Guild Role Positions
 * @method PATCH
 */
export type EditGuildRolePositionsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles`;

/**
 * Edit Guild Role
 * @method PATCH
 */
export type EditGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles/${RoleID}`;

/**
 * Delete Guild Role
 * @method DELETE
 */
export type DeleteGuildRoleEndpoint<
  GuildID extends snowflake = snowflake,
  RoleID extends snowflake = snowflake,
> = `/guilds/${GuildID}/roles/${RoleID}`;

/**
 * Get Guild Prune Count
 * @method GET
 */
export type GetGuildPruneCountEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/prune`;

/**
 * Begin Guild Prune
 * @method POST
 */
export type BeginGuildPruneEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/prune`;

/**
 * Get Guild Voice Regions
 * @method GET
 */
export type GetGuildVoiceRegionsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/regions`;

/**
 * Get Guild Invites
 * @method GET
 */
export type GetGuildInvitesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/invites`;

/**
 * Get Guild Integrations
 * @method GET
 */
export type GetGuildIntegrationsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/integrations`;

/**
 * Delete Guild Integration
 * @method DELETE
 */
export type DeleteGuildIntegrationEndpoint<
  GuildID extends snowflake = snowflake,
  IntegrationID extends snowflake = snowflake,
> = `/guilds/${GuildID}/integrations/${IntegrationID}`;

/**
 * Get Guild Widget Settings
 * @method GET
 */
export type GetGuildWidgetSettingsEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget`;

/**
 * Edit Guild Widget
 * @method PATCH
 */
export type EditGuildWidgetEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget`;

/**
 * Get Guild Widget
 * @method GET
 */
export type GetGuildWidgetEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget.json`;

/**
 * Get Guild Vanity URL
 * @method GET
 */
export type GetGuildVanityURLEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/vanity-url`;

/**
 * Get Guild Widget Image
 * @method GET
 */
export type GetGuildWidgetImageEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/widget.png`;

/**
 * Get Guild Welcome Screen
 * @method GET
 */
export type GetGuildWelcomeScreenEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/welcome-screen`;

/**
 * Edit Guild Welcome Screen
 * @method PATCH
 */
export type EditGuildWelcomeScreenEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/welcome-screen`;

/**
 * Edit Current User Voice State
 * @method PATCH
 */
export type EditCurrentUserVoiceStateEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/voice-states/@me`;

/**
 * Edit User Voice State
 * @method PATCH
 */
export type EditUserVoiceStateEndpoint<
  GuildID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/guilds/${GuildID}/voice-states/${UserID}`;

/**
 * Get Current User
 * @method GET
 */
export type GetCurrentUserEndpoint = `/users/@me`;

/**
 * Get User
 * @method GET
 */
export type GetUserEndpoint<
  UserID extends snowflake = snowflake,
> = `/users/${UserID}`;

/**
 * Edit Current User
 * @method PATCH
 */
export type EditCurrentUserEndpoint = `/users/@me`;

/**
 * Get Current User Guilds
 * @method GET
 */
export type GetCurrentUserGuildsEndpoint = `/users/@me/guilds`;

/**
 * Leave Guild
 * @method DELETE
 */
export type LeaveGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/users/@me/guilds/${GuildID}`;

/**
 * Create DM
 * @method POST
 */
export type CreateDMEndpoint = `/users/@me/channels`;

/**
 * Create Group DM
 * @method POST
 */
export type CreateGroupDMEndpoint = `/users/@me/channels`;

/**
 * Get User Connections
 * @method GET
 */
export type GetUserConnectionsEndpoint = `/users/@me/connections`;

/**
 * Get Invite
 * @method GET
 */
export type GetInviteEndpoint<
  InviteCode extends string = string,
> = `/invites/${InviteCode}`;

/**
 * Delete Invite
 * @method DELETE
 */
export type DeleteInviteEndpoint<
  InviteCode extends string = string,
> = `/invites/${InviteCode}`;

/**
 * List Voice Regions
 * @method GET
 */
export type ListVoiceRegionsEndpoint = `/voice/regions`;

/**
 * Get Guild Audit Log
 * @method GET
 */
export type GetGuildAuditLogEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/audit-logs`;

/**
 * Get Guild Template
 * @method GET
 */
export type GetGuildTemplateEndpoint<
  TemplateCode extends string = string,
> = `/guilds/templates/${TemplateCode}`;

/**
 * Create Guild from Guild Template
 * @method POST
 */
export type CreateGuildfromGuildTemplateEndpoint<
  TemplateCode extends string = string,
> = `/guilds/templates/${TemplateCode}`;

/**
 * Get Guild Templates
 * @method GET
 */
export type GetGuildTemplatesEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/templates`;

/**
 * Create Guild Template
 * @method POST
 */
export type CreateGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/templates`;

/**
 * Sync Guild Template
 * @method PUT
 */
export type SyncGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  TemplateCode extends string = string,
> = `/guilds/${GuildID}/templates/${TemplateCode}`;

/**
 * Edit Guild Template
 * @method PATCH
 */
export type EditGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  TemplateCode extends string = string,
> = `/guilds/${GuildID}/templates/${TemplateCode}`;

/**
 * Delete Guild Template
 * @method DELETE
 */
export type DeleteGuildTemplateEndpoint<
  GuildID extends snowflake = snowflake,
  TemplateCode extends string = string,
> = `/guilds/${GuildID}/templates/${TemplateCode}`;

/**
 * Create Stage Instance
 * @method POST
 */
export type CreateStageInstanceEndpoint = `/stage-instances`;

/**
 * Get Stage Instance
 * @method GET
 */
export type GetStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Edit Stage Instance
 * @method PATCH
 */
export type EditStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Delete Stage Instance
 * @method DELETE
 */
export type DeleteStageInstanceEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/stage-instances/${ChannelID}`;

/**
 * Get Channel
 * @method GET
 */
export type GetChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}`;

/**
 * Edit Channel
 * @method PATCH
 */
export type EditChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}`;

/**
 * Get Channel Messages
 * @method GET
 */
export type GetChannelMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages`;

/**
 * Get Channel Message
 * @method GET
 */
export type GetChannelMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * Create Message
 * @method POST
 */
export type CreateMessageEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages`;

/**
 * Crosspost Message
 * @method POST
 */
export type CrosspostMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/crosspost`;

/**
 * Create Reaction
 * @method PUT
 */
export type CreateReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  Emoji extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${Emoji}/@me`;

/**
 * Delete Own Reaction
 * @method DELETE
 */
export type DeleteOwnReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  Emoji extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${Emoji}/@me`;

/**
 * Delete User Reaction
 * @method DELETE
 */
export type DeleteUserReactionEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  Emoji extends string = string,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${Emoji}/${UserID}`;

/**
 * Get Reactions
 * @method GET
 */
export type GetReactionsEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  Emoji extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${Emoji}`;

/**
 * Delete All Reactions
 * @method DELETE
 */
export type DeleteAllReactionsEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions`;

/**
 * Delete All Reactions for Emoji
 * @method DELETE
 */
export type DeleteAllReactionsforEmojiEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
  Emoji extends string = string,
> = `/channels/${ChannelID}/messages/${MessageID}/reactions/${Emoji}`;

/**
 * Edit Message
 * @method PATCH
 */
export type EditMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * Delete Message
 * @method DELETE
 */
export type DeleteMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}`;

/**
 * Bulk Delete Messages
 * @method POST
 */
export type BulkDeleteMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/bulk-delete`;

/**
 * Edit Channel Permissions
 * @method PUT
 */
export type EditChannelPermissionsEndpoint<
  ChannelID extends snowflake = snowflake,
  OverwriteID extends snowflake = snowflake,
> = `/channels/${ChannelID}/permissions/${OverwriteID}`;

/**
 * Get Channel Invites
 * @method GET
 */
export type GetChannelInvitesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/invites`;

/**
 * Create Channel Invite
 * @method POST
 */
export type CreateChannelInviteEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/invites`;

/**
 * Delete Channel Permission
 * @method DELETE
 */
export type DeleteChannelPermissionEndpoint<
  ChannelID extends snowflake = snowflake,
  OverwriteID extends snowflake = snowflake,
> = `/channels/${ChannelID}/permissions/${OverwriteID}`;

/**
 * Follow News Channel
 * @method POST
 */
export type FollowNewsChannelEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/followers`;

/**
 * Trigger Typing Indicator
 * @method POST
 */
export type TriggerTypingIndicatorEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/typing`;

/**
 * Get Pinned Messages
 * @method GET
 */
export type GetPinnedMessagesEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins`;

/**
 * Pin Message
 * @method PUT
 */
export type PinMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins/${MessageID}`;

/**
 * Unpin Message
 * @method DELETE
 */
export type UnpinMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/pins/${MessageID}`;

/**
 * Group DM Add Recipient
 * @method PUT
 */
export type GroupDMAddRecipientEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/recipients/${UserID}`;

/**
 * Group DM Remove Recipient
 * @method DELETE
 */
export type GroupDMRemoveRecipientEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/recipients/${UserID}`;

/**
 * Start Thread with Message
 * @method POST
 */
export type StartThreadwithMessageEndpoint<
  ChannelID extends snowflake = snowflake,
  MessageID extends snowflake = snowflake,
> = `/channels/${ChannelID}/messages/${MessageID}/threads`;

/**
 * Start Thread without Message
 * @method POST
 */
export type StartThreadwithoutMessageEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads`;

/**
 * Join Thread
 * @method PUT
 */
export type JoinThreadEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/@me`;

/**
 * Add Thread Member
 * @method PUT
 */
export type AddThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * Leave Thread
 * @method DELETE
 */
export type LeaveThreadEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/@me`;

/**
 * Remove Thread Member
 * @method DELETE
 */
export type RemoveThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * Get Thread Member
 * @method GET
 */
export type GetThreadMemberEndpoint<
  ChannelID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members/${UserID}`;

/**
 * List Thread Members
 * @method GET
 */
export type ListThreadMembersEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/thread-members`;

/**
 * List Active Threads
 * @method GET
 */
export type ListActiveThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads/active`;

/**
 * List Public Archived Threads
 * @method GET
 */
export type ListPublicArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads/archived/public`;

/**
 * List Private Archived Threads
 * @method GET
 */
export type ListPrivateArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/threads/archived/private`;

/**
 * List Joined Private Archived Threads
 * @method GET
 */
export type ListJoinedPrivateArchivedThreadsEndpoint<
  ChannelID extends snowflake = snowflake,
> = `/channels/${ChannelID}/users/@me/threads/archived/private`;

/**
 * List Guild Emojis
 * @method GET
 */
export type ListGuildEmojisEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis`;

/**
 * Get Guild Emoji
 * @method GET
 */
export type GetGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * Create Guild Emoji
 * @method POST
 */
export type CreateGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis`;

/**
 * Edit Guild Emoji
 * @method PATCH
 */
export type EditGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * Delete Guild Emoji
 * @method DELETE
 */
export type DeleteGuildEmojiEndpoint<
  GuildID extends snowflake = snowflake,
  EmojiID extends snowflake = snowflake,
> = `/guilds/${GuildID}/emojis/${EmojiID}`;

/**
 * List Scheduled Events for Guild
 * @method GET
 */
export type ListScheduledEventsforGuildEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events`;

/**
 * Create Guild Scheduled Event
 * @method POST
 */
export type CreateGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events`;

/**
 * Get Guild Scheduled Event
 * @method GET
 */
export type GetGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  Guild_scheduled_eventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${Guild_scheduled_eventID}`;

/**
 * Edit Guild Scheduled Event
 * @method PATCH
 */
export type EditGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  Guild_scheduled_eventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${Guild_scheduled_eventID}`;

/**
 * Delete Guild Scheduled Event
 * @method DELETE
 */
export type DeleteGuildScheduledEventEndpoint<
  GuildID extends snowflake = snowflake,
  Guild_scheduled_eventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${Guild_scheduled_eventID}`;

/**
 * Get Guild Scheduled Event Users
 * @method GET
 */
export type GetGuildScheduledEventUsersEndpoint<
  GuildID extends snowflake = snowflake,
  Guild_scheduled_eventID extends snowflake = snowflake,
> = `/guilds/${GuildID}/scheduled-events/${Guild_scheduled_eventID}/users`;

/**
 * Get Sticker
 * @method GET
 */
export type GetStickerEndpoint<
  StickerID extends snowflake = snowflake,
> = `/stickers/${StickerID}`;

/**
 * List Nitro Sticker Packs
 * @method GET
 */
export type ListNitroStickerPacksEndpoint = `/sticker-packs`;

/**
 * List Guild Stickers
 * @method GET
 */
export type ListGuildStickersEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers`;

/**
 * Get Guild Sticker
 * @method GET
 */
export type GetGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * Create Guild Sticker
 * @method POST
 */
export type CreateGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers`;

/**
 * Edit Guild Sticker
 * @method PATCH
 */
export type EditGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * Delete Guild Sticker
 * @method DELETE
 */
export type DeleteGuildStickerEndpoint<
  GuildID extends snowflake = snowflake,
  StickerID extends snowflake = snowflake,
> = `/guilds/${GuildID}/stickers/${StickerID}`;

/**
 * Get Gateway
 * @method GET
 */
export type GetGatewayEndpoint = `/gateway`;

/**
 * Get Gateway Bot
 * @method GET
 */
export type GetGatewayBotEndpoint = `/gateway/bot`;

/**
 * Get Current Bot Application Information
 * @method GET
 */
export type GetCurrentBotApplicationInformationEndpoint =
  `/oauth2/applications/@me`;

/**
 * Get Current Authorization Information
 * @method GET
 */
export type GetCurrentAuthorizationInformationEndpoint = `/oauth2/@me`;

/**
 * Get Entitlements
 * @method GET
 */
export type GetEntitlementsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/entitlements`;

/**
 * Get Entitlement
 * @method GET
 */
export type GetEntitlementEndpoint<
  ApplicationID extends snowflake = snowflake,
  EntitlementID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/entitlements/${EntitlementID}`;

/**
 * Get SKUs
 * @method GET
 */
export type GetSKUsEndpoint<
  ApplicationID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/skus`;

/**
 * Consume SKU
 * @method POST
 */
export type ConsumeSKUEndpoint<
  ApplicationID extends snowflake = snowflake,
  EntitlementID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/entitlements/${EntitlementID}/consume`;

/**
 * Delete Test Entitlement
 * @method DELETE
 */
export type DeleteTestEntitlementEndpoint<
  ApplicationID extends snowflake = snowflake,
  EntitlementID extends snowflake = snowflake,
> = `/applications/${ApplicationID}/entitlements/${EntitlementID}`;

/**
 * Create Purchase Discount
 * @method PUT
 */
export type CreatePurchaseDiscountEndpoint<
  SkuID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/store/skus/${SkuID}/discounts/${UserID}`;

/**
 * Delete Purchase Discount
 * @method DELETE
 */
export type DeletePurchaseDiscountEndpoint<
  SkuID extends snowflake = snowflake,
  UserID extends snowflake = snowflake,
> = `/store/skus/${SkuID}/discounts/${UserID}`;

export type Endpoint =
  | CreateInteractionResponseEndpoint
  | GetOriginalInteractionResponseEndpoint
  | EditOriginalInteractionResponseEndpoint
  | DeleteOriginalInteractionResponseEndpoint
  | CreateFollowupMessageEndpoint
  | GetFollowupMessageEndpoint
  | EditFollowupMessageEndpoint
  | DeleteFollowupMessageEndpoint
  | GetGlobalApplicationCommandsEndpoint
  | CreateGlobalApplicationCommandEndpoint
  | GetGlobalApplicationCommandEndpoint
  | EditGlobalApplicationCommandEndpoint
  | DeleteGlobalApplicationCommandEndpoint
  | BulkOverwriteGlobalApplicationCommandsEndpoint
  | GetGuildApplicationCommandsEndpoint
  | CreateGuildApplicationCommandEndpoint
  | GetGuildApplicationCommandEndpoint
  | EditGuildApplicationCommandEndpoint
  | DeleteGuildApplicationCommandEndpoint
  | BulkOverwriteGuildApplicationCommandsEndpoint
  | GetGuildApplicationCommandPermissionsEndpoint
  | GetApplicationCommandPermissionsEndpoint
  | EditApplicationCommandPermissionsEndpoint
  | BatchEditApplicationCommandPermissionsEndpoint
  | CreateWebhookEndpoint
  | GetChannelWebhooksEndpoint
  | GetGuildWebhooksEndpoint
  | GetWebhookEndpoint
  | GetWebhookwithTokenEndpoint
  | EditWebhookEndpoint
  | EditWebhookwithTokenEndpoint
  | DeleteWebhookEndpoint
  | DeleteWebhookwithTokenEndpoint
  | ExecuteWebhookEndpoint
  | ExecuteSlackCompatibleWebhookEndpoint
  | ExecuteGitHubCompatibleWebhookEndpoint
  | GetWebhookMessageEndpoint
  | EditWebhookMessageEndpoint
  | DeleteWebhookMessageEndpoint
  | CreateGuildEndpoint
  | GetGuildEndpoint
  | GetGuildPreviewEndpoint
  | EditGuildEndpoint
  | DeleteGuildEndpoint
  | GetGuildChannelsEndpoint
  | CreateGuildChannelEndpoint
  | EditGuildChannelPositionsEndpoint
  | ListActiveGuildThreadsEndpoint
  | GetGuildMemberEndpoint
  | ListGuildMembersEndpoint
  | SearchGuildMembersEndpoint
  | AddGuildMemberEndpoint
  | EditGuildMemberEndpoint
  | EditCurrentMemberEndpoint
  | EditCurrentUserNickEndpoint
  | AddGuildMemberRoleEndpoint
  | RemoveGuildMemberRoleEndpoint
  | RemoveGuildMemberEndpoint
  | GetGuildBansEndpoint
  | GetGuildBanEndpoint
  | CreateGuildBanEndpoint
  | RemoveGuildBanEndpoint
  | GetGuildRolesEndpoint
  | CreateGuildRoleEndpoint
  | EditGuildRolePositionsEndpoint
  | EditGuildRoleEndpoint
  | DeleteGuildRoleEndpoint
  | GetGuildPruneCountEndpoint
  | BeginGuildPruneEndpoint
  | GetGuildVoiceRegionsEndpoint
  | GetGuildInvitesEndpoint
  | GetGuildIntegrationsEndpoint
  | DeleteGuildIntegrationEndpoint
  | GetGuildWidgetSettingsEndpoint
  | EditGuildWidgetEndpoint
  | GetGuildWidgetEndpoint
  | GetGuildVanityURLEndpoint
  | GetGuildWidgetImageEndpoint
  | GetGuildWelcomeScreenEndpoint
  | EditGuildWelcomeScreenEndpoint
  | EditCurrentUserVoiceStateEndpoint
  | EditUserVoiceStateEndpoint
  | GetCurrentUserEndpoint
  | GetUserEndpoint
  | EditCurrentUserEndpoint
  | GetCurrentUserGuildsEndpoint
  | LeaveGuildEndpoint
  | CreateDMEndpoint
  | CreateGroupDMEndpoint
  | GetUserConnectionsEndpoint
  | GetInviteEndpoint
  | DeleteInviteEndpoint
  | ListVoiceRegionsEndpoint
  | GetGuildAuditLogEndpoint
  | GetGuildTemplateEndpoint
  | CreateGuildfromGuildTemplateEndpoint
  | GetGuildTemplatesEndpoint
  | CreateGuildTemplateEndpoint
  | SyncGuildTemplateEndpoint
  | EditGuildTemplateEndpoint
  | DeleteGuildTemplateEndpoint
  | CreateStageInstanceEndpoint
  | GetStageInstanceEndpoint
  | EditStageInstanceEndpoint
  | DeleteStageInstanceEndpoint
  | GetChannelEndpoint
  | EditChannelEndpoint
  | GetChannelMessagesEndpoint
  | GetChannelMessageEndpoint
  | CreateMessageEndpoint
  | CrosspostMessageEndpoint
  | CreateReactionEndpoint
  | DeleteOwnReactionEndpoint
  | DeleteUserReactionEndpoint
  | GetReactionsEndpoint
  | DeleteAllReactionsEndpoint
  | DeleteAllReactionsforEmojiEndpoint
  | EditMessageEndpoint
  | DeleteMessageEndpoint
  | BulkDeleteMessagesEndpoint
  | EditChannelPermissionsEndpoint
  | GetChannelInvitesEndpoint
  | CreateChannelInviteEndpoint
  | DeleteChannelPermissionEndpoint
  | FollowNewsChannelEndpoint
  | TriggerTypingIndicatorEndpoint
  | GetPinnedMessagesEndpoint
  | PinMessageEndpoint
  | UnpinMessageEndpoint
  | GroupDMAddRecipientEndpoint
  | GroupDMRemoveRecipientEndpoint
  | StartThreadwithMessageEndpoint
  | StartThreadwithoutMessageEndpoint
  | JoinThreadEndpoint
  | AddThreadMemberEndpoint
  | LeaveThreadEndpoint
  | RemoveThreadMemberEndpoint
  | GetThreadMemberEndpoint
  | ListThreadMembersEndpoint
  | ListActiveThreadsEndpoint
  | ListPublicArchivedThreadsEndpoint
  | ListPrivateArchivedThreadsEndpoint
  | ListJoinedPrivateArchivedThreadsEndpoint
  | ListGuildEmojisEndpoint
  | GetGuildEmojiEndpoint
  | CreateGuildEmojiEndpoint
  | EditGuildEmojiEndpoint
  | DeleteGuildEmojiEndpoint
  | ListScheduledEventsforGuildEndpoint
  | CreateGuildScheduledEventEndpoint
  | GetGuildScheduledEventEndpoint
  | EditGuildScheduledEventEndpoint
  | DeleteGuildScheduledEventEndpoint
  | GetGuildScheduledEventUsersEndpoint
  | GetStickerEndpoint
  | ListNitroStickerPacksEndpoint
  | ListGuildStickersEndpoint
  | GetGuildStickerEndpoint
  | CreateGuildStickerEndpoint
  | EditGuildStickerEndpoint
  | DeleteGuildStickerEndpoint
  | GetGatewayEndpoint
  | GetGatewayBotEndpoint
  | GetCurrentBotApplicationInformationEndpoint
  | GetCurrentAuthorizationInformationEndpoint
  | GetEntitlementsEndpoint
  | GetEntitlementEndpoint
  | GetSKUsEndpoint
  | ConsumeSKUEndpoint
  | DeleteTestEntitlementEndpoint
  | CreatePurchaseDiscountEndpoint
  | DeletePurchaseDiscountEndpoint;
