import { GuildChannelPayload } from "../channels/guild.ts";

export interface GuildPayload {
  id: string;
  name: string;
  icon: string | null;
  icon_hash?: string | null;
  splash: string | null;
  discovery_splash: string | null;
  owner?: boolean;
  owner_id: string;
  permissions?: string;
  region?: string | null;
  afk_channel_id: string | null;
  afk_timeout: number;
  widget_enabled: boolean;
  widget_channel_id?: string | null;
  verification_level: number;
  default_message_notifications: number;
  explicit_content_filter: number;
  // roles: RolePayload[];
  // emojis: EmojiPayload[];
  // features: GuildFeature[];
  mfa_level: number;
  application_id: string | null;
  system_channel_id: string | null;
  system_channel_flags: number;
  joined_at?: string;
  large?: boolean;
  unavailable?: boolean;
  member_count?: number;
  // voice_states?: VoiceStatePayload[];
  // members?: MemberPayload[];
  channels?: GuildChannelPayload[];
  // presences?: PresencePayload[];
  max_presences?: number | null;
  max_members?: number;
  vanity_url_code: string | null;
  description: string | null;
  banner: string | null;
  premium_tier: number;
  premium_subscription_count?: number;
  preferred_locale: string;
  public_updates_channel_id: string | null;
  max_video_channel_users?: number;
  approximate_member_count?: number;
  approximate_presence_count?: number;
  // welcome_screen?: WelcomeScreenPayload;
  nsfw_level: number;
  // stage_instances?: StageInstancePayload[];
  // stickers?: StickerPayload[];
}
