name: Format

on:
  push:
    branches: [v3]
  pull_request:
    branches: [v3]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Formatting Check
        run: deno fmt -c deno.json --check
